version: '3'

services:
  backend:
    build: .
    depends_on:
      - "mysql.livraria"
    links:
      - mysql.livraria
    ports:
      - "8081:8081"
  mysql.livraria:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: livraria123
      MYSQL_DATABASE: livraria
    volumes:
     - mysql.livraria.monolito:/var/lib/mysql
volumes:
  mysql.livraria.monolito:

